### ISSUE TITLE
KappaTools using own boost lib, even if a boost version is installed.

### ISSUE THREAD

**Issue by claria** [KappaAnalysis/KappaTools#2]
I am pulling in boost using the CMSSW environment. But KappaTools still used its own boost library leading to warnings like this in my code.

/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/gcc/4.8.1/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.8.1/../../../../x86_64-redhat-linux-gnu/bin/ld: warning: libboost_regex.so.1.57.0, needed by /nfs/dust/cms/user/gsieber/dijetana/ana/CMSSW_7_2_3/external/slc6_amd64_gcc481/lib/libKToolbox.so, may conflict with libboost_regex.so.1.51.0.

Can't we just remove this boost downloading mechanism in KappaTools and require boost to be installed by the user?

**Comment by JoramBerger** [comment]
Yes, please. I advocated that for years.

**Comment by claria** [comment]
fixed.
